import turtle 
x = turtle.Turtle() 


def squarre(): 
    x.fillcolor('yellow')   
    x.begin_fill() 
    x.left(0) 
    x.forward(200) 
    x.left(90) 
    x.forward(200)
    x.left(90) 
    x.forward(200)
    x.left(90) 
    x.forward(200)
    x.end_fill() 
def pantalon(): 
    x.fillcolor('brown')   
    x.begin_fill() 
    x.left(90) 
    x.forward(200) 
    x.left(90) 
    x.forward(50)
    x.left(90) 
    x.forward(200)
    x.left(90) 
    x.forward(50)
    x.end_fill() 

def yeux():
    x.fillcolor('white')   
    x.begin_fill() 
    x.setpos(20, 100)
    x.left(90) 
    x.forward(50) 
    x.left(90) 
    x.forward(50)
    x.left(90) 
    x.forward(50)
    x.left(90) 
    x.forward(50)
    x.end_fill()
    x.begin_fill() 
    x.setpos(120, 100)
    x.left(90) 
    x.forward(50) 
    x.left(90) 
    x.forward(50)
    x.left(90) 
    x.forward(50)
    x.left(90) 
    x.forward(50)
    x.end_fill()


def bouche():
    x.fillcolor('red')   
    x.begin_fill() 
    x.setpos(20, 60)
    x.left(90) 
    x.forward(100) 
    x.left(90) 
    x.forward(20)
    x.left(90) 
    x.forward(100)
    x.left(90) 
    x.forward(20)
    x.end_fill()

def bras():
    x.fillcolor('yellow')   
    x.begin_fill() 
    x.setpos(200, 60)
    x.left(90) 
    x.forward(100) 
    x.left(90) 
    x.forward(20)
    x.left(90) 
    x.forward(100)
    x.left(90) 
    x.forward(20)
    x.end_fill()
    x.begin_fill() 
    x.setpos(-100, 60)
    x.left(90) 
    x.forward(100) 
    x.left(90) 
    x.forward(20)
    x.left(90) 
    x.forward(100)
    x.left(90) 
    x.forward(20)
    x.end_fill()
 
def jambes():
    x.fillcolor('brown')   
    x.begin_fill() 
    x.setpos(20, 00)
    x.left(90) 
    x.forward(30) 
    x.left(90) 
    x.forward(100)
    x.left(90) 
    x.forward(30)
    x.left(90) 
    x.forward(100)
    x.end_fill()
    x.begin_fill() 
    x.setpos(180, 00)
    x.left(90) 
    x.forward(30) 
    x.left(90) 
    x.forward(100)
    x.left(90) 
    x.forward(30)
    x.left(90) 
    x.forward(100)
    x.end_fill()

def piscine():
    x.fillcolor('blue')   
    x.begin_fill() 
    x.setpos(-50, -250)
    x.left(90) 
    x.forward(300) 
    x.left(90) 
    x.forward(150)
    x.left(90) 
    x.forward(300)
    x.left(90) 
    x.forward(150)
    x.end_fill()

def txt():  
    x.up() 
    x.setpos(-100, 50)    
    x.down()    
    x.color('orange')    
    x.write("Sponge Bob splash piscine", font=( 
      "Algerian", 22, "bold"))   




squarre()  
pantalon()
yeux()
bouche()
bras()
jambes()
piscine()
txt() 
x.ht()



